package sports

type Sport string

const (
	AlpineSki         Sport = "AlpineSki"
	BackcountrySki    Sport = "BackcountrySki"
	Badminton         Sport = "Badminton"
	Canoeing          Sport = "Canoeing"
	Crossfit          Sport = "Crossfit"
	EBikeRide         Sport = "EBikeRide"
	Elliptical        Sport = "Elliptical"
	EMountainBikeRide Sport = "EMountainBikeRide"
	Golf              Sport = "Golf"
	GravelRide        Sport = "GravelRide"
	Handcycle         Sport = "Handcycle"
	HIIT              Sport = "HighIntensityIntervalTraining"
	Hike              Sport = "Hike"
	IceSkate          Sport = "IceSkate"
	InlineSkate       Sport = "InlineSkate"
	Kayaking          Sport = "Kayaking"
	Kitesurf          Sport = "Kitesurf"
	MountainBikeRide  Sport = "MountainBikeRide"
	NordicSki         Sport = "NordicSki"
	Pickleball        Sport = "Pickleball"
	Pilates           Sport = "Pilates"
	Racquetball       Sport = "Racquetball"
	Ride              Sport = "Ride"
	RockClimbing      Sport = "RockClimbing"
	RollerSki         Sport = "RollerSki"
	Rowing            Sport = "Rowing"
	Run               Sport = "Run"
	Sail              Sport = "Sail"
	Skateboard        Sport = "Skateboard"
	Snowboard         Sport = "Snowboard"
	Snowshoe          Sport = "Snowshoe"
	Soccer            Sport = "Soccer"
	Squash            Sport = "Squash"
	StairStepper      Sport = "StairStepper"
	StandUpPaddling   Sport = "StandUpPaddling"
	Surfing           Sport = "Surfing"
	Swim              Sport = "Swim"
	TableTennis       Sport = "TableTennis"
	Tennis            Sport = "Tennis"
	TrailRun          Sport = "TrailRun"
	Velomobile        Sport = "Velomobile"
	VirtualRide       Sport = "VirtualRide"
	VirtualRow        Sport = "VirtualRow"
	VirtualRun        Sport = "VirtualRun"
	Walk              Sport = "Walk"
	WeightTraining    Sport = "WeightTraining"
	Wheelchair        Sport = "Wheelchair"
	Windsurf          Sport = "Windsurf"
	Workout           Sport = "Workout"
	Yoga              Sport = "Yoga"
)
