name: SAST
on:
  pull_request: {}
  schedule:
    - cron: "35 9 * * *"

permissions:
  contents: read

jobs:
  sast: # v2026.07.21
    uses: ockendenjo/actions/.github/workflows/sast.yaml@1927116938e4146cc2fb47f52b2126c799c27ef9 # zizmor: ignore[stale-action-refs,ref-version-mismatch]
